@API_HostAddress = http://localhost:5000/api

###

// To create a new menu category.

POST {{API_HostAddress}}/MenuCategory
Content-Type: application/json
Accept: application/json

{
  "name": "Appetizers"
}

###


###

// To create a new menu item.

POST {{API_HostAddress}}/MenuItem
Content-Type: application/json
Accept: application/json

{
  "name": "Margherita Pizza4",
  "description": "Classic pizza with tomato, mozzarella, and basil",
  "price": 13,
  "menuCategoryId": "D2634AAE-BFE5-4139-92D2-F0D96D3B08EF",
  "ingredientIds": [
    "26BE6B7B-5152-49A8-8980-4CA63F0081C5"
  ]
}


###
