@API_HostAddress = http://localhost:5000/api

// To update an existing menu item.

PUT {{API_HostAddress}}/MenuItem/fc0e8638-f584-4fd8-82a9-fea84f3eed39
Content-Type: application/json
Accept: application/json

{
  "name": "BBQ Chicken Pizza",
  "description": "Grilled chicken, BBQ sauce, and red onions",
  "price": 12.50,
  "ingredientIds": [
    "8C7FC3D2-8BD6-4634-AE36-4207D439C2A4"
  ]
}

###

// To delete an existing menu item.

DELETE {{API_HostAddress}}/MenuItem/fc0e8638-f584-4fd8-82a9-fea84f3eed39
Accept: application/json

###