@API_HostAddress = http://localhost:5000/api

// To get a specific table by its ID.
GET {{API_HostAddress}}/tables/3fe3e456-28ff-4d1a-8747-2654243f9794
Accept: application/json

###
// To get all tables.

GET {{API_HostAddress}}/tables
Accept: application/json

###