@API_HostAddress = http://localhost:5000/api

// To update an existing table.

PUT {{API_HostAddress}}/tables/21b2af68-4041-48ef-bb9b-3a21627d6777
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Table Name",
  "capacity": 6,
  "isUsed": true,
  "status": "Reserved"
}

###

// To update the status of a table.

PUT {{API_HostAddress}}/tables/{id}/status
Content-Type: application/json
Accept: application/json

"PendingPayment"

###
// To delete an existing table.

DELETE {{API_HostAddress}}/tables/21b2af68-4041-48ef-bb9b-3a21627d6777
Accept: application/json

###