@API_HostAddress = http://localhost:5000/api

###

// To update a customer's information.

PUT {{API_HostAddress}}/CustomerInformation/4402E7A0-1D66-4A85-87A3-D39BF06A1724
Content-Type: application/json
Accept: application/json

{
  "phoneNumber": "987654321",
  "additionalInstructions": "Deliver to the back door.",
  "address": "123 New Street, City"
}

###