@API_HostAddress = http://localhost:5000/api

###

// To create a new reservation.

POST {{API_HostAddress}}/reservations
Content-Type: application/json
Accept: application/json

{
  "phoneNumber": "123456789",
  "name": "Smith",
  "dateTime": "2025-02-10T19:00:00Z",
  "capacityNeeded": 4
}

###
