@API_HostAddress = http://localhost:5000/api

###
// To get a specific reservation by its ID.

GET {{API_HostAddress}}/reservations/e5923a9a-b482-4955-83de-13bc5180b9d8
Accept: application/json

###
// To get all reservations.

GET {{API_HostAddress}}/reservations
Accept: application/json

###
// To get reservations for a specific date.

GET {{API_HostAddress}}/reservations/2025-09-23
Accept: application/json

###