@API_HostAddress = http://localhost:5000/api

###

// To create a new reservation.

POST {{API_HostAddress}}/reservations
Content-Type: application/json
Accept: application/json

{
  "phoneNumber": "123456789",
  "name": "Tom",
  "scheduledFor": "2025-09-22T19:00:00Z",
  "capacityNeeded": 4
}

###
