@API_HostAddress = http://localhost:5000/api

// To assign a reservation to a table.

PUT {{API_HostAddress}}/reservations/13108707-9eee-4ac9-9e3d-80b527e54439/table?tableId=d1c9326d-1744-4835-b3f3-038c1a765b79
Accept: application/json

###

// To update an existing reservation.

PUT {{API_HostAddress}}/reservations/e5923a9a-b482-4955-83de-13bc5180b9d8
Content-Type: application/json
Accept: application/json

{
  "dateTime": "2025-02-11T20:00:00Z",
  "capacityNeeded": 5,
  "tableId": "F960CF2D-2529-4E0B-A3E5-1E691AE9CAC3"
}

###

// To delete an existing reservation.

DELETE {{API_HostAddress}}/reservations/e5923a9a-b482-4955-83de-13bc5180b9d8
Accept: application/json

###