@API_HostAddress = http://localhost:5000/api

POST {{API_HostAddress}}/Order/dinein
Content-Type: application/json
Accept: application/json

{
  "orderDateTime": "2026-02-07T12:00:00Z",
  "tableId": "367d061a-aad9-4f38-8257-36cc71916924",
  "orderItems": [
    {
      "menuItemId": "6EDD0176-C9EF-4F10-9693-F502CD2257B6",
      "specialInstructions": "No onions, extra cheese",
      "ingredients": [
        {
          "ingredientId": "B8461E8E-BBB1-4FFF-8ACE-9C2460390538",
          "quantity": 2
        },
        {
          "ingredientId": "C8F9CB59-D588-49C0-9C43-DA589ED4543C",
          "quantity": 1
        }
      ]
    },
    {
      "menuItemId": "AF7FD522-493E-4987-ABB0-4CDE845745AD",
      "specialInstructions": null
    }
  ]
}

###
