@API_HostAddress = http://localhost:5000/api

### Get all ingredients

GET {{API_HostAddress}}/Ingredients
Accept: application/json

### Get ingredients filtered by tags

GET {{API_HostAddress}}/Ingredients?tags=spicy
Accept: application/json

### Get a specific ingredient by its ID

GET {{API_HostAddress}}/Ingredients/26be6b7b-5152-49a8-8980-4ca63f0081c5
Accept: application/json