@API_HostAddress = http://localhost:5000/api

###

// To create a new ingredient.

POST {{API_HostAddress}}/Ingredients
Content-Type: application/json
Accept: application/json

{
  "name": "Mozzarella",
  "price": 2.50,
  "ingredientType": "Cheese"
}

###