@API_HostAddress = http://localhost:5000/api

// To get a specific menu category by its ID.

GET {{API_HostAddress}}/57a02042-fc02-4d4e-a4d1-abae0896c95a
Accept: application/json

###

// To get all menu categories.

GET {{API_HostAddress}}/menu-categories
Accept: application/json

###