@API_HostAddress = http://localhost:5000/api

// To get a specific menu category by its ID.

GET {{API_HostAddress}}/MenuCategory/0135f22f-8d28-4286-98c1-1eda42816779
Accept: application/json

###

// To get all menu categories.

GET {{API_HostAddress}}/MenuCategory/menu-categories
Accept: application/json

###