@API_HostAddress = http://localhost:5000/api

###

// To get a specific order by its ID.

GET {{API_HostAddress}}/orders/C93FA2FE-918A-4B90-9841-342C6A84E716
Accept: application/json

###

// To get all orders (without filtering by status).

GET {{API_HostAddress}}/orders
Accept: application/json

###

// To get all orders filtered by status (e.g., only "Ongoing" orders).
GET {{API_HostAddress}}/orders?orderStatus=Ongoing
Accept: application/json

###

GET {{API_HostAddress}}/orders/non-dinein-orders?orderType=Takeaway
Accept: application/json


###

GET {{API_HostAddress}}/orders/non-dinein-orders?orderType=Delivery
Accept: application/json


###

// To get all Finished orders.

GET {{API_HostAddress}}/orders?orderStatus=Finished
Accept: application/json

###

// To get all cancelled orders.

GET {{API_HostAddress}}/orders?orderStatus=Cancelled
Accept: application/json

###
