@API_HostAddress = http://localhost:5000/api

// To create one dineIn order with 2 order items. 
// One order item with 2 extra ingredients and one without extra ingredients.

POST {{API_HostAddress}}/orders/dinein
Content-Type: application/json
Accept: application/json

{
  "dateTime": "2026-04-07T12:00:00Z",
  "tableId": "74b952f6-9793-4d48-bbde-ce7f6b5cfecd",
  "orderItems": [
    {
      "menuItemId": "0026375D-9736-4B94-ABA5-3E7644643DFF",
      "specialInstructions": "No onions, extra cheese",
      "extraIngredients": [
        {
          "ingredientId": "012BD3A0-F0A6-4A8D-9AE7-703EEE731302",
          "quantity": 2
        },
        {
          "ingredientId": "2201F320-8642-4275-BB32-324D592EB355",
          "quantity": 1
        }
      ],
      "removedIngredientIds": []
    },
    {
      "menuItemId": "0A762473-96D2-4409-A8CA-631C8AAA1236",
      "specialInstructions": null,
      "extraIngredients": [],
      "removedIngredientIds": []
    }
  ]
}

###
# To create one takeaway order with 2 order items.
# One order item with 2 extra ingredients and one without extra ingredients.

POST {{API_HostAddress}}/orders/takeaway
Content-Type: application/json
Accept: application/json

{
  "dateTime": "2026-02-07T12:30:00Z",
  "customerInformation": {
    "phoneNumber": "123456789",
    "additionalInstructions": "Please call on arrival.",
    "orderCompletionType": "Immediate",
    "preferredPaymentMethod": "Cash",
    "expectedOrderCompletion": null
  },
  "orderItems": [
    {
      "menuItemId": "0026375D-9736-4B94-ABA5-3E7644643DFF",
      "specialInstructions": "No onions, extra cheese",
      "extraIngredients": [
        {
          "ingredientId": "012BD3A0-F0A6-4A8D-9AE7-703EEE731302",
          "quantity": 2
        },
        {
          "ingredientId": "2201F320-8642-4275-BB32-324D592EB355",
          "quantity": 1
        }
      ],
      "removedIngredientIds": []
    },
    {
      "menuItemId": "0A762473-96D2-4409-A8CA-631C8AAA1236",
      "specialInstructions": null,
      "extraIngredients": [],
      "removedIngredientIds": []
    }
  ]
}



###
# To create one delivery order with 2 order items.
# One order item with 2 extra ingredients and one without extra ingredients.

POST {{API_HostAddress}}/orders/delivery
Content-Type: application/json
Accept: application/json

{
  "dateTime": "2026-02-07T13:00:00Z",
  "customerInformation": {
    "phoneNumber": "123456789",
    "address": "123 Main Street, City, Country",
    "additionalInstructions": "Leave at the doorstep.",
    "orderCompletionType": "Immediate",
    "preferredPaymentMethod": "Card",
    "expectedOrderCompletion": null
  },
  "orderItems": [
    {
      "menuItemId": "0026375D-9736-4B94-ABA5-3E7644643DFF",
      "specialInstructions": "Extra spicy",
      "extraIngredients": [
        {
          "ingredientId": "012BD3A0-F0A6-4A8D-9AE7-703EEE731302",
          "quantity": 2
        },
        {
          "ingredientId": "2201F320-8642-4275-BB32-324D592EB355",
          "quantity": 1
        }
      ],
      "removedIngredientIds": []
    },
    {
      "menuItemId": "0A762473-96D2-4409-A8CA-631C8AAA1236",
      "specialInstructions": null,
      "extraIngredients": [],
      "removedIngredientIds": []
    }
  ]
}

###
