@API_HostAddress = http://localhost:5000/api

// Use this for order example you need to copy Id
POST {{API_HostAddress}}/orders/dinein
Content-Type: application/json
Accept: application/json

{
  "createdAt": "2026-02-07T12:00:00Z",
  "tableId": "C9B75583-CAB5-457B-B87B-C89B9E2E6A36",
  "orderItems": [
    {
      "menuItemId": "AF7FD522-493E-4987-ABB0-4CDE845745AD",
      "specialInstructions": "No onions, extra cheese",
      "ingredients": [
        {
          "ingredientId": "DFCC60D2-E025-45FD-9FE0-BC6198335E3B",
          "quantity": 2
        },
        {
          "ingredientId": "3EBB3F19-ED25-4FE5-B17B-2FC369A4FADC",
          "quantity": 1
        }
      ]
    },
    {
      "menuItemId": "6EDD0176-C9EF-4F10-9693-F502CD2257B6",
      "specialInstructions": null
    }
  ]
}

###

// Split an order by moving specific items from one order to another.

POST {{API_HostAddress}}/orders/21b2af68-4041-48ef-bb9b-3a21627d6777/split
Content-Type: application/json
Accept: application/json

{
  "orderItemIds": [
    "72a57583-87d3-4c58-9a60-988bb7a5cf9b"
  ]
}

###

// To apply a discount to an existing order.

PATCH {{API_HostAddress}}/orders/C93FA2FE-918A-4B90-9841-342C6A84E716/apply-discount?discount=50
Accept: application/json

###

// Create a Table and Extract tableId
POST {{API_HostAddress}}/tables
Content-Type: application/json
Accept: application/json

{
  "name": "Test Table",
  "numberOfPeople": 4
}


###


// To change the table assigned to an order.

// 1. Create a table
// 2. Create order with created table,
// 3. Create table and proceed with change table

PATCH {{API_HostAddress}}/orders/c93fa2fe-918a-4b90-9841-342c6a84e716/change-table
Content-Type: application/json
Accept: application/json

"7676ce30-f27e-4adb-acf0-8ad42c1b4cb4"

###

// To update the status of an order.

PATCH {{API_HostAddress}}/orders/8793ab1d-61fd-4227-a739-1c29ccda3008/status
Content-Type: application/json
Accept: application/json

"Closed"

###

// To update the type of an order, changing it from **Dine-In to Takeaway**.

PATCH {{API_HostAddress}}/orders/c93fa2fe-918a-4b90-9841-342c6a84e716/type
Content-Type: application/json
Accept: application/json

{
  "newOrderType": "Takeaway",
  "phoneNumber": "123456789"
}

###

// To update the type of an order, changing it from **Dine-In to Delivery**.

PATCH {{API_HostAddress}}/orders/C93FA2FE-918A-4B90-9841-342C6A84E716/type
Content-Type: application/json
Accept: application/json

{
  "newOrderType": "Delivery",
  "phoneNumber": "987654321",
  "address": "456 New Street, City",
  "additionalInstructions": "Ring the doorbell twice.",
  "orderCompletionType": "Immediate",
  "preferredPaymentMethod": "Card",
  "expectedOrderCompletion": null
}

###

// To update the type of an order, changing it from **Delivery to Dine-In**.

PATCH {{API_HostAddress}}/orders/C93FA2FE-918A-4B90-9841-342C6A84E716/type
Content-Type: application/json
Accept: application/json

{
  "newOrderType": "DineIn",
  "tableId": "9165C97C-5477-4EED-A566-F6FEC0E84694"
}

###

// To delete an existing order.

DELETE {{API_HostAddress}}/Order/fd8d1d7f-81ce-4207-8bd1-61f6467c100d
Accept: application/json

###
