@API_HostAddress = http://localhost:5000

###

// To add order items to an existing order.
POST {{API_HostAddress}}/orders/E67B14CD-40BC-4088-BA5F-51406B40F87B/order-items
Content-Type: application/json
Accept: application/json

[
  {
    "menuItemId": "129DC430-0D6C-4933-B7F9-A677B7BD1BFE",
    "specialInstructions": "Extra cheese, no onions",
    "extraIngredients": [
      {
        "ingredientId": "A4458F4C-55D7-4BB9-9FE6-6E7B88BC96EA",
        "quantity": 2
      },
      {
        "ingredientId": "26BE6B7B-5152-49A8-8980-4CA63F0081C5",
        "quantity": 1
      }
    ],
    "removedIngredients": [
      {
        "ingredientId": "3F94D539-6882-40F5-A079-FA8D7091BAC3"
      }
    ]
  },
  {
    "menuItemId": "02C8DC6D-4E25-4B54-904A-C39C37173735",
    "specialInstructions": null,
    "extraIngredients": [],
    "removedIngredients": []
  }
]