@API_HostAddress = http://localhost:5000

###

// To update an order item.

PUT {{API_HostAddress}}/orders/e67b14cd-40bc-4088-ba5f-51406b40f87b/order-items/8e7325e9-bca4-4e71-8e67-767bbd121fba
Content-Type: application/json
Accept: application/json

{
  "specialInstructions": "Add extra mushrooms",
  "discount": 10.00,
  "extraIngredients": [
    {
      "ingredientId": "20a15b68-b2ae-4053-87b2-264eef92cc54",
      "quantity": 3
    }
  ],
  "removedIngredients": [
    {
      "ingredientId": "3f94d539-6882-40f5-a079-fa8d7091bac3"
    }
  ]
}


###
// Update Order Item Status

PATCH {{API_HostAddress}}/orders/E67B14CD-40BC-4088-BA5F-51406B40F87B/order-items/8e7325e9-bca4-4e71-8e67-767bbd121fba/status
Content-Type: application/json
Accept: application/json

"Served"


###

// To delete an order item.

DELETE {{API_HostAddress}}/orders/E67B14CD-40BC-4088-BA5F-51406B40F87B/order-items/8e7325e9-bca4-4e71-8e67-767bbd121fba
Accept: application/json


###