@API_HostAddress = http://localhost:5000/api

// To get a specific order item by its ID.

GET {{API_HostAddress}}/orders/e67b14cd-40bc-4088-ba5f-51406b40f87b/order-items/534a44a2-5eac-49ea-8e2f-556645534ee6
Accept: application/json

###

// To get all order items for a specific order.

GET {{API_HostAddress}}/orders/e67b14cd-40bc-4088-ba5f-51406b40f87b/order-items
Accept: application/json

###